version: '3.3'
services:
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: magicbus
      # So you don't have to use root, but you can if you like
      MYSQL_USER: magicbus
      # You can use whatever password you like
      MYSQL_PASSWORD: magicbus
      # Password for root access
      MYSQL_ROOT_PASSWORD: magicbus
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
# Names our volume
volumes:
  my-db: